#!/usr/bin/env bash

question="\nAsk the Magic 8 Ball a question"
options=(
"It is certain"
"It is decidedly so"
"Without a doubt"
"Yes, definitely"
"You may rely on it"
"As I see it, yes"
"Most likely"
"Outlook good"
"Yes"
"Signs point to yes"
"Reply hazy try again"
"Ask again later"
"Better not tell you now"
"Cannot predict now"
"Concentrate and ask again"
"Don't count on it"
"My reply is no"
"My sources say no"
"Outlook not so good"
"Very doubtful"
)

while : ; do
    question=$(echo -e "$question" | dmenu "$@" -p "Magic 8 Ball" | xargs echo | bc 2>&1)
    [[ $question ]] || break # if no question asked, exit
    question="\n${options[$((RANDOM%20))]}"
done
