#!/usr/bin/env bash

draw_line () {
	for i in {1..10}; do
		printf "―"
	done
}

menu_list="  run\n  term\n  web\n  music\n  file\n  edit\n  view\n  todo\n  calc\n  man\n  top\n$(draw_line)\n  exit"
dmenucmd="dmenu -c -i -l 13"
cmd=$(echo -e "$menu_list" | eval "$dmenucmd")

case $cmd in
	*run)
		dmenu_prog -c -l 20 ;;
	*term)
		tabbed -c st -w ;;
	*web)
		surf_open ;;
	*music)
		st -e cmus ;;
	*file)
		thunar > /dev/null 2>&1 ;;
	*edit) # TODO dont open if dmenu returned empty
		st -e vim -p "$(dmenu_browse -c)" ;;
	*view)
		sxiv "$(dmenu_browse -c)" ;;
	*todo)
		dmenu_todo -c ;;
	*calc)
		dmenu_calc -c -l 1;;
	*man)
		manprog=$(dmenu_man -c -l 20)
		manname=$(echo "$manprog" | cut -d " " -f 2)
		st -t "$manname" -e man $manprog ;;
	*top)
		st -g 68x6 -e htop ;;
	*exit)
		# dmenu_quit -c ;;
		cbpp-exit ;;
	*)
		$cmd
esac

exit 0
