#!/usr/bin/env bash

draw_line () {
	for i in {1..10}; do
		printf "―"
	done
}

menu_list="  run\n  term\n  web\n  file\n  edit\n  view\n  todo\n  calc\n  man\n  htop\n$(draw_line)\n  exit\n"
dmenucmd="dmenu -c -i -l 12"
cmd=$(echo -e "$menu_list" | eval "$dmenucmd")

case $cmd in
	*run)
		dmenu_prog -c -l 20 ;;
	*term)
		tabbed -c st -w ;;
	*web)
		firefox > /dev/null 2>&1 ;;
	*file)
		thunar > /dev/null 2>&1 ;;
	*edit) # TODO dont open if dmenu returned empty
		st -e vim -p "$(dmenu_browse -c)" ;;
	*view)
		sxiv "$(dmenu_browse -c)" ;;
	*todo)
		dmenu_todo -c ;;
	*calc)
		dmenu_calc -c -l 1;;
	*man)
		st -e man $(dmenu_man -c -l 20) ;;
	*htop)
		st -g 68x6 -e htop ;;
	*exit)
		# dmenu_quit -c ;;
		cbpp-exit ;;
	*)
		$cmd
esac

exit 0
